<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\MySql.Data.Tests.csproj" total="14" errors="10" failures="3" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2011-10-09" time="16:53:22">
  <environment nunit-version="2.5.10.11092" clr-version="2.0.50727.5446" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="C:\Program Files (x86)\NUnit 2.5.10\bin\net-2.0" machine-name="PENGJILU_1" user="pengjilu" user-domain="FEINNO" />
  <culture-info current-culture="zh-CN" current-uiculture="zh-CN" />
  <test-suite type="Project" name="D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\MySql.Data.Tests.csproj" executed="True" result="Failure" success="False" time="1.846" asserts="0">
    <results>
      <test-suite type="Assembly" name="D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\bin\net-2.0\Debug\MySql.Data.Tests.dll" executed="True" result="Failure" success="False" time="1.846" asserts="0">
        <results>
          <test-suite type="Namespace" name="MySql" executed="True" result="Failure" success="False" time="1.846" asserts="0">
            <results>
              <test-suite type="Namespace" name="Data" executed="True" result="Failure" success="False" time="1.846" asserts="0">
                <results>
                  <test-suite type="Namespace" name="MySqlClient" executed="True" result="Failure" success="False" time="1.846" asserts="0">
                    <results>
                      <test-suite type="Namespace" name="Tests" executed="True" result="Failure" success="False" time="1.845" asserts="0">
                        <results>
                          <test-suite type="TestFixture" name="CommandTests" executed="True" result="Failure" success="False" time="1.844" asserts="0">
                            <results>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.CloneCommand" executed="True" result="Error" success="False" time="0.053" asserts="0">
                                <failure>
                                  <message><![CDATA[SetUp : Unknown database 'db526-a'
TearDown : NUnit.Framework.AssertionException : 未将对象引用设置到对象的实例。]]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.Tests.BaseTest.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 251
在 MySql.Data.MySqlClient.Tests.CommandTests.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 35
--TearDown
在 MySql.Data.MySqlClient.Tests.BaseTest.Close() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 208
在 MySql.Data.MySqlClient.Tests.BaseTest.Teardown() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 260
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.CloseReaderAfterFailedConvert" executed="True" result="Error" success="False" time="0.072" asserts="0">
                                <failure>
                                  <message><![CDATA[SetUp : Unknown database 'db526-a'
TearDown : NUnit.Framework.AssertionException : 未将对象引用设置到对象的实例。]]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.Tests.BaseTest.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 251
在 MySql.Data.MySqlClient.Tests.CommandTests.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 35
--TearDown
在 MySql.Data.MySqlClient.Tests.BaseTest.Close() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 208
在 MySql.Data.MySqlClient.Tests.BaseTest.Teardown() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 260
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.CtorTest" executed="True" result="Success" success="True" time="0.211" asserts="0" />
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.DefaultCommandTimeout" executed="True" result="Failure" success="False" time="0.012" asserts="0">
                                <failure>
                                  <message><![CDATA[SetUp : Unknown database 'db526-a']]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.Tests.BaseTest.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 251
在 MySql.Data.MySqlClient.Tests.CommandTests.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 35
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.DeleteTest" executed="True" result="Failure" success="False" time="0.108" asserts="0">
                                <failure>
                                  <message><![CDATA[Table 'db526-a.test' doesn't exist]]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.Tests.CommandTests.DeleteTest() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 137
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.ExecuteWithOneBadQuery" executed="True" result="Error" success="False" time="0.129" asserts="0">
                                <failure>
                                  <message><![CDATA[Connection must be valid and open.
TearDown : NUnit.Framework.AssertionException : 未将对象引用设置到对象的实例。]]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.Tests.CommandTests.ExecuteWithOneBadQuery() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 403
--TearDown
在 MySql.Data.MySqlClient.Tests.BaseTest.Close() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 208
在 MySql.Data.MySqlClient.Tests.BaseTest.Teardown() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 260
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.GenWarnings" executed="True" result="Error" success="False" time="0.247" asserts="0">
                                <failure>
                                  <message><![CDATA[MySql.Data.MySqlClient.MySqlException : Table 'db526-a.test' doesn't exist]]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.MySqlStream.OpenPacket() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\MySqlStream.cs:行号 199
在 MySql.Data.MySqlClient.NativeDriver.ReadResult(UInt64& affectedRows, Int64& lastInsertId) 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\NativeDriver.cs:行号 566
在 MySql.Data.MySqlClient.MySqlDataReader.GetResultSet() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\datareader.cs:行号 840
在 MySql.Data.MySqlClient.MySqlDataReader.NextResult() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\datareader.cs:行号 932
在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior) 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\command.cs:行号 448
在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\command.cs:行号 336
在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\command.cs:行号 312
在 MySql.Data.MySqlClient.Tests.BaseTest.execSQL(String sql) 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 318
在 MySql.Data.MySqlClient.Tests.CommandTests.GenWarnings() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 336
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.InsertingPreparedNulls" executed="True" result="Error" success="False" time="0.164" asserts="0">
                                <failure>
                                  <message><![CDATA[MySql.Data.MySqlClient.MySqlException : Table 'db526-a.test' doesn't exist]]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.MySqlStream.OpenPacket() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\MySqlStream.cs:行号 199
在 MySql.Data.MySqlClient.NativeDriver.ReadResult(UInt64& affectedRows, Int64& lastInsertId) 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\NativeDriver.cs:行号 566
在 MySql.Data.MySqlClient.MySqlDataReader.GetResultSet() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\datareader.cs:行号 840
在 MySql.Data.MySqlClient.MySqlDataReader.NextResult() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\datareader.cs:行号 932
在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior) 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\command.cs:行号 448
在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\command.cs:行号 336
在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\command.cs:行号 312
在 MySql.Data.MySqlClient.Tests.BaseTest.execSQL(String sql) 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 318
在 MySql.Data.MySqlClient.Tests.CommandTests.InsertingPreparedNulls() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 228
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.InsertTest" executed="True" result="Failure" success="False" time="0.177" asserts="0">
                                <failure>
                                  <message><![CDATA[Table 'db526-a.test' doesn't exist]]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.Tests.CommandTests.InsertTest() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 70
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.PreparedInsertUsingReader" executed="True" result="Error" success="False" time="0.122" asserts="0">
                                <failure>
                                  <message><![CDATA[MySql.Data.MySqlClient.MySqlException : Table 'db526-a.test' doesn't exist]]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.MySqlStream.OpenPacket() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\MySqlStream.cs:行号 199
在 MySql.Data.MySqlClient.NativeDriver.ReadResult(UInt64& affectedRows, Int64& lastInsertId) 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\NativeDriver.cs:行号 566
在 MySql.Data.MySqlClient.MySqlDataReader.GetResultSet() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\datareader.cs:行号 840
在 MySql.Data.MySqlClient.MySqlDataReader.NextResult() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\datareader.cs:行号 932
在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior) 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\command.cs:行号 448
在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\command.cs:行号 336
在 MySql.Data.MySqlClient.Tests.CommandTests.PreparedInsertUsingReader() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 265
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.SetNullConnection" executed="True" result="Error" success="False" time="0.010" asserts="0">
                                <failure>
                                  <message><![CDATA[SetUp : Unknown database 'db526-a'
TearDown : NUnit.Framework.AssertionException : Unknown database 'db526-a']]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.Tests.BaseTest.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 251
在 MySql.Data.MySqlClient.Tests.CommandTests.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 35
--TearDown
在 MySql.Data.MySqlClient.Tests.BaseTest.Close() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 208
在 MySql.Data.MySqlClient.Tests.BaseTest.Teardown() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 260
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.TableWithOVer100Columns" executed="True" result="Error" success="False" time="0.082" asserts="0">
                                <failure>
                                  <message><![CDATA[SetUp : Unknown database 'db526-a'
TearDown : NUnit.Framework.AssertionException : Unknown database 'db526-a']]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.Tests.BaseTest.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 251
在 MySql.Data.MySqlClient.Tests.CommandTests.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 35
--TearDown
在 MySql.Data.MySqlClient.Tests.BaseTest.Close() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 208
在 MySql.Data.MySqlClient.Tests.BaseTest.Teardown() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 260
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.UpdateTest" executed="True" result="Error" success="False" time="0.082" asserts="0">
                                <failure>
                                  <message><![CDATA[SetUp : Unknown database 'db526-a'
TearDown : NUnit.Framework.AssertionException : Unknown database 'db526-a']]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.Tests.BaseTest.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 251
在 MySql.Data.MySqlClient.Tests.CommandTests.Setup() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 35
--TearDown
在 MySql.Data.MySqlClient.Tests.BaseTest.Close() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 208
在 MySql.Data.MySqlClient.Tests.BaseTest.Teardown() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 260
]]></stack-trace>
                                </failure>
                              </test-case>
                              <test-case name="MySql.Data.MySqlClient.Tests.CommandTests.UseAffectedRows" executed="True" result="Error" success="False" time="0.197" asserts="0">
                                <failure>
                                  <message><![CDATA[MySql.Data.MySqlClient.MySqlException : Table 'db526-a.test' doesn't exist]]></message>
                                  <stack-trace><![CDATA[在 MySql.Data.MySqlClient.MySqlStream.OpenPacket() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\MySqlStream.cs:行号 199
在 MySql.Data.MySqlClient.NativeDriver.ReadResult(UInt64& affectedRows, Int64& lastInsertId) 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\NativeDriver.cs:行号 566
在 MySql.Data.MySqlClient.MySqlDataReader.GetResultSet() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\datareader.cs:行号 840
在 MySql.Data.MySqlClient.MySqlDataReader.NextResult() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\datareader.cs:行号 932
在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior) 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\command.cs:行号 448
在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\command.cs:行号 336
在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Provider\Source\command.cs:行号 312
在 MySql.Data.MySqlClient.Tests.BaseTest.execSQL(String sql) 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\BaseTest.cs:行号 318
在 MySql.Data.MySqlClient.Tests.CommandTests.UseAffectedRows() 位置 D:\Research\mysql-connector-net-5.2.6-src - 2010\MySql.Data\Tests\Source\CommandTests.cs:行号 454
]]></stack-trace>
                                </failure>
                              </test-case>
                            </results>
                          </test-suite>
                        </results>
                      </test-suite>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>